apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptor-new-deploy
  labels:
    app: adaptor-new-app
  annotations:
spec:
  selector:
    matchLabels:
      app: adaptor-new-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: adaptor-new-app
    spec:
      containers:
      - name: adaptor-new
        image: registry.digitalocean.com/mapofzones/stats-adaptor:d716a5b2
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: adaptor_DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: adaptor_new_DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: adaptor_new_DB_PASS
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
