apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculation-service-deploy
  labels:
    app: calculation-service-app
  annotations:
spec:
  selector:
    matchLabels:
      app: calculation-service-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: calculation-service-app
    spec:
      containers:
      - name: calculation-service
        image: registry.digitalocean.com/mapofzones/calculation-service:2cdca4eb
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: endpoint-checker_DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: endpoint-checker_DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: endpoint-checker_DB_PASS
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: calculations_MONGODB_URI
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
