apiVersion: v1
kind: Secret
metadata:
  name: prodsecret
  namespace: prod
type: Opaque
stringData:
  watcher_rabbitmq : amqp://<login>:<pass>@<ip>:<port>
  db_graphql : http://<ip>:<port>/v1/graphql
  processor_rabbitmq : amqp://<login>:<pass>@<ip>:<port>
  processor_db : postgres://<user>:<pass>@<ip>:<port>/<db>
  adaptor_DB_URL : jdbc:postgresql://<ip>:<port>/<db>
  adaptor_DB_USER : <db_user>
  adaptor_DB_PASS : <db_user_pass>
  hasura_db_url : postgres://<user>:<pass>@<ip>:<port>/<db>
  hasura_admin_secret : <pass>
  endpoint-checker_DB_URL : jdbc:postgresql://<ip>:<port>/<db>
  endpoint-checker_DB_USER : <db_user>
  endpoint-checker_DB_PASS : <db_user_pass>
  zone-height-checker_DB_URL : jdbc:postgresql://<ip>:<port>/<db>
  zone-height-checker_DB_USER : <db_user>
  zone-height-checker_DB_PASS : <db_user_pass>
  zone-height-checker_CHAT_ID : <telegram_chat_id>
  zone-height-checker_TOKEN : <telegram_bot_token>
  command-executor_ACCESS_TOKEN: <executor_ACCESS_TOKEN>
  command-executor_CLUSTER_ID: <executor_CLUSTER_ID>
  adaptor_new_DB_USER: <adaptor_new_DB_USER>
  adaptor_new_DB_PASS: <adaptor_new_DB_PASS>
# kubectl apply -f ./kubernetes/secrets/prod-secret.yaml