apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura2
  namespace: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hasura2
  template:
    metadata:
      labels:
        app: hasura2
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hasura2
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hasura2
        image: hasura/graphql-engine:v1.3.3
        imagePullPolicy: IfNotPresent
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: prodsecret
              key: hasura_db_url
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
           secretKeyRef:
             name: prodsecret
             key: hasura_admin_secret
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          value: front
        - name: HASURA_GRAPHQL_MIGRATIONS_DIR
          value: /hasura-migrations
        - name: HASURA_GRAPHQL_METADATA_DIR
          value: /hasura-metadata
        ## enable the console served by server. It is recommended to disable this in production
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2000m"
          requests:
            memory: "1024Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
          protocol: TCP
