apiVersion: apps/v1
kind: Deployment
metadata:
  name: desmos-watcher-deploy
  labels:
    app: desmos-watcher-app
  annotations:
spec:
  selector:
    matchLabels:
      app: desmos-watcher-app

  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: desmos-watcher-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - desmos-watcher-app
            topologyKey: "kubernetes.io/hostname"
      hostAliases:
      - ip: "159.89.250.255"
        hostnames:
        - "api.mapofzones.com"
      containers:

      - name: desmos-mainnet
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-desmos:8e153110
        env:
          - name: chain_id
            value: "desmos-mainnet"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
          - name: queue
            value: "blocks_v3"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "35Mi"
            cpu: "15m"
          limits:
            memory: "128Mi"
            cpu: "100m"
