#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: kichainlogged-watcher-deploy
#  labels:
#    app: kichainlogged-watcher-app
#  annotations:
#spec:
#  selector:
#    matchLabels:
#      app: kichainlogged-watcher-app
#
#  replicas: 1
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 2
#      maxUnavailable: 0
#  template:
#    metadata:
#      labels:
#        app: kichainlogged-watcher-app
#    spec:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - kichainlogged-watcher-app
#            topologyKey: "kubernetes.io/hostname"
#      hostAliases:
#      - ip: "159.89.250.255"
#        hostnames:
#        - "api.mapofzones.com"
#      containers:
#
#      - name: kichain-2
##        image: registry.digitalocean.com/mapofzones/cosmos-watcher-kichain:db23bf21
#        image: registry.digitalocean.com/mapofzones/cosmos-watcher-kichaintest:a9b0074e
#        env:
#          - name: chain_id
#            value: "kichain-2"
#          - name: rabbitmq
#            valueFrom:
#              secretKeyRef:
#                name: prodsecret
#                key: watcher_rabbitmq
#          - name: graphql
#            valueFrom:
#              secretKeyRef:
#                name: prodsecret
#                key: db_graphql
#          - name: queue
##            value: "blocks_v3"
#            value: "blocks_v3_debug"
#        imagePullPolicy: Always
#        resources:
#          requests:
#            memory: "150Mi"
#            cpu: "30m"
#          limits:
#            memory: "256Mi"
#            cpu: "250m"
