apiVersion: apps/v1
kind: Deployment
metadata:
  name: teritori-watcher-deploy
  labels:
    app: teritori-watcher-app
spec:
  selector:
    matchLabels:
      app: teritori-watcher-app

  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: teritori-watcher-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - teritori-watcher-app
            topologyKey: "kubernetes.io/hostname"
      hostAliases:
      - ip: "159.89.250.255"
        hostnames:
        - "api.mapofzones.com"
      containers:

      - name: teritori-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-teritori:5939ebc8
        env:
          - name: chain_id
            value: "teritori-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
          - name: queue
            value: "blocks_v3_2"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
