apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-matcher-deploy
  labels:
    app: token-matcher-app
  annotations:
spec:
  selector:
    matchLabels:
      app: token-matcher-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: token-matcher-app
    spec:
      containers:
      - name: token-matcher
        image: registry.digitalocean.com/mapofzones/token-matcher:8ff6a294
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: endpoint-checker_DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: endpoint-checker_DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: endpoint-checker_DB_PASS
          - name: TM_SYNC_TIME
            value: "120s"
          - name: TM_THREADS
            value: "2"
          - name: PF_SYNC_TIME
            value: "60s"
          - name: PF_THREADS
            value: "1"
          - name: TPF_SYNC_TIME
            value: "60s"
          - name: TPF_THREADS
            value: "1"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
